#![no_std]
#![allow(
    clippy::missing_const_for_fn,
    reason = "Shader entry points are generated by macro tooling and are kept in a conventional form."
)]

use spirv_std::glam::{Vec4, vec4};
use spirv_std::spirv;

#[spirv(fragment)]
pub fn main_fs(output: &mut Vec4) {
    *output = vec4(1.0, 0.0, 0.0, 1.0);
}
