[package]
name = "fusion-rhi-metal"
description = ""
documentation = ""
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib"]
path = "MetalRHI.rs"

[dependencies]
fusion-rhi-core = { path = "../" }

