[package]
name = "fusion-rhi-core"
description = ""
documentation = ""
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib"]
path = "RHICore.rs"

[dependencies]
bitflags = "2.9.4"
